apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: car-serv-ingress
  namespace: car-serv
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: car-serv.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: car-serv-service
                port:
                  number: 80

