apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: car-serv
spec:
  destination:
    namespace: car-serv
    server: https://kubernetes.default.svc
  project: default
  source:
    path: v02-argocd-carserv/template
    repoURL: https://github.com/nvn2kit/argocd-test.git
    targetRevision: main

